Add CMake support
swift-project/pilotclient pull request #220
Opened 2023-10-25 18:42 UTC by ltoenning

Fixes #211 

:warning: Before going into a release version, this should be tested by some users beforehand.

2023-10-27 00:01 UTC, oktal3700 commented on scripts/build.py
> +            subprocess.check_call(["cmake", "--build", ".", "--target", "test"], env=dict(os.environ))
How about `subprocess.check_call(["ctest", "--verbose"]` so we see the full test output on CI

2023-10-30 02:12 UTC, oktal3700 requested changes
- [ ] I guess you intended to rename the unittests to remove the `black` prefix
- [ ] There is one test which passes with qmake but is skipped with cmake: `BlackCoreTest::CTestContext`

2023-10-30 02:18 UTC, oktal3700 commented on .gitignore
Lines 5, 36, 37 & 54 can be removed. Those files were artifacts of qmake.

2023-10-30 02:19 UTC, oktal3700 commented on .gitignore
> +dist/
These two directories are created only in the root of the source tree, right? So they can be prepended with a `/` prefix to limit their scope there:
```
/out/
/dist/
```

2023-10-30 02:21 UTC, oktal3700 commented on default.json
Could be renamed to `version.json`

2023-10-30 02:23 UTC, oktal3700 commented on scripts/build.py
> +            return
It makes sense to bundle CSL2XSB for both 32bit and 64bit Windows. Both can be used with X-Plane (with 64bit xswiftbus, of course)

2023-10-30 02:25 UTC, oktal3700 commented on src/plugins/simulator/fs9/lobbyclient.h
Prefer putting this into a separate commit

2023-10-30 02:26 UTC, oktal3700 commented on src/plugins/simulator/fsxcommon/simconnectwindows.h
> +#include <QtCore/QtGlobal>
Should be `#include <QtGlobal>`

2023-10-30 02:27 UTC, oktal3700 commented on tests/blackmisc/CMakeLists.txt
> +#)
Commented out unittest?

2023-11-01 19:18 UTC, oktal3700 commented on .gitignore
Seems like this should be squashed into a9abbf4

2023-11-12 20:40 UTC, ltoenning commented
Merged with staging branch. https://github.com/swift-project/pilotclient/commit/1deaeba58431f3879e35cdc5604da5944a3c919f
Fixed #220.

2023-11-12 20:40 UTC, closed without merging